### PR TITLE
Remove shared_ptr cimport

### PR DESCRIPTION
**Pull request by kchua78**
@zachmayer This is the PR to modify fasttext

### CODE REVIEW

**Comment by kchua78** [comment]
@zachmayer made some more changes to make it work with cython 0.21

**Comment by zachmayer** [comment]
@kchua78 Were you able to build this with cython 0.21?

**Comment by kchua78** [comment]
Yes. It built and tests passed with cython 0.21

**Comment by zachmayer** [comment]
Awesome!

**Comment by smillet15** [comment]
How are we going to release this? Custom dr version and push to artifactory?

**Comment by zachmayer** [comment]
@smillet15 Yes, that's the plan.  I'm not sure how to push to artifactory— could you help with that?

**Comment by smillet15** [comment]
Yup. Once this is merged I can bump the version and push.

**Comment by zachmayer** [comment]
@kchua78 Any reason not to merge this branch, since for now we're using this repo for internal testing only?

**Comment by zachmayer** [comment]
@kchua78 @sabariraju I'm going to merge this in 2 hours, unless I hear otherwise.

**Comment by zachmayer** [comment]
@smillet15 Done

**Pull request merged**
